-- Seed: 40 most commonly examined VA conditions — C&P exam prep data
-- Run in Supabase SQL Editor AFTER running schema.sql

INSERT INTO dbq_criteria (condition_name, dbq_form_number, key_symptoms, exam_tips, common_mistakes) VALUES

('PTSD', 'DBQ 21-0960P-3',
 ARRAY['Intrusive thoughts/flashbacks','Nightmares','Hypervigilance','Exaggerated startle response','Avoidance of triggers','Irritability/angry outbursts','Difficulty concentrating','Sleep disturbance'],
 'Describe your WORST days, not your best. The examiner needs to understand how PTSD affects your ability to work, maintain relationships, and handle daily life. Be specific: "I wake up 3-4 times per night from nightmares," not "I don''t sleep well." Mention every symptom even if you think it''s minor — panic attacks, difficulty in crowds, road rage, isolation from family, missed work days. If you''ve had suicidal thoughts, say so. If your spouse/family has noticed behavior changes, bring a buddy statement. Describe how your worst week looks compared to a normal person''s week.',
 'Downplaying symptoms to appear strong — the examiner rates what you report. Saying "I''m fine" or "I manage" when you''re actually struggling. Not mentioning alcohol/substance use as a coping mechanism. Dressing up and appearing well-groomed for the exam when most days you don''t. Not connecting symptoms to work impact — "I can''t hold a job because of anger outbursts" is ratable, "I get angry sometimes" is not. Failing to mention relationship failures, social isolation, or suicidal ideation.'),

('Major depressive disorder', 'DBQ 21-0960P-2',
 ARRAY['Depressed mood','Loss of interest in activities','Sleep disturbance','Fatigue/loss of energy','Feelings of worthlessness','Difficulty concentrating','Appetite/weight changes','Suicidal ideation'],
 'Describe the frequency and duration of depressive episodes — how many days per month are you significantly impaired? Explain functional impact: missed work, inability to maintain hygiene, withdrawal from family/friends, inability to complete household tasks. Mention medication side effects. If you have good days and bad days, describe both but emphasize how the bad days affect your overall reliability and productivity. Bring documentation of any psychiatric hospitalizations or emergency visits.',
 'Only describing current moment rather than the pattern over time. Saying "the medication helps" without explaining remaining symptoms — being medicated and still symptomatic is key to higher ratings. Not mentioning cognitive symptoms like memory problems and inability to concentrate. Appearing "put together" at the exam and not explaining that it took extraordinary effort. Not connecting depression to inability to maintain work or relationships.'),

('Generalized anxiety disorder', 'DBQ 21-0960P-2',
 ARRAY['Excessive worry','Restlessness','Muscle tension','Sleep disturbance','Irritability','Difficulty concentrating','Fatigue','Panic attacks'],
 'Quantify your panic attacks — how often, how long, what triggers them. Describe avoidance behaviors: do you avoid driving, crowds, stores, social situations? Explain how anxiety affects work performance — missed deadlines, inability to focus, conflict with coworkers. Mention physical symptoms: chest tightness, sweating, racing heart, GI distress. Describe your worst anxiety episodes in detail. If anxiety prevents you from leaving the house some days, say so explicitly.',
 'Minimizing panic attacks or not counting them accurately. Not mentioning avoidance behaviors that limit daily life. Describing anxiety in vague terms ("I worry a lot") instead of specific functional impacts ("I had to leave work 3 times last month due to panic attacks"). Not connecting anxiety to sleep problems, GI issues, or relationship difficulties. Taking anti-anxiety medication before the exam to appear calmer than usual.'),

('Traumatic brain injury', 'DBQ 21-0960C-1',
 ARRAY['Memory impairment','Difficulty concentrating','Headaches','Dizziness/balance problems','Sensitivity to light/noise','Sleep disturbance','Irritability/mood changes','Slowed processing speed'],
 'TBI is rated on 10 facets: memory, judgment, social interaction, orientation, motor activity, visual-spatial orientation, subjective symptoms, neurobehavioral effects, communication, and consciousness. Address EACH facet. Describe cognitive problems specifically: "I forget appointments, get lost driving familiar routes, can''t follow multi-step instructions." Bring neuropsychological testing results if available. Describe headaches separately as they''re rated under DC 8100. Mention any history of blast exposure even if you didn''t lose consciousness.',
 'Underreporting the blast event — any exposure to blast overpressure counts, not just direct hits. Not getting neuropsychological testing before the exam. Failing to separate TBI residuals from PTSD symptoms — they can be rated separately. Not mentioning cognitive decline compared to pre-service baseline. Saying "I''m fine" because you''ve adapted to the impairments over years. Not bringing someone who can describe your behavioral/cognitive changes.'),

('Sleep apnea', 'DBQ 21-0960S-1',
 ARRAY['Witnessed apnea episodes','Excessive daytime sleepiness','Morning headaches','Frequent nighttime awakenings','Loud snoring','Difficulty concentrating during day','Unrefreshing sleep','CPAP usage'],
 'The key rating thresholds are: 0% (asymptomatic), 30% (persistent daytime hypersomnolence), 50% (requires CPAP), 100% (requires tracheostomy or has cor pulmonale). If you use a CPAP, bring your compliance data showing regular use. Describe daytime symptoms even with CPAP: do you still fall asleep during the day, struggle to stay awake driving, need naps? If your sleep study is old, get a new one. Describe how sleep apnea affects your work — falling asleep at desk, inability to drive safely, cognitive fog.',
 'Not having a current sleep study. Not using CPAP consistently (VA checks compliance records). Not describing symptoms that persist DESPITE CPAP use — this matters for higher ratings. Not connecting sleep apnea to a service-connected condition (PTSD, weight gain from medications, neck/throat injury). Bringing an at-home sleep test instead of an in-lab polysomnography when the diagnosis is borderline.'),

('Lumbosacral strain', 'DBQ 21-0960M-14',
 ARRAY['Pain on forward flexion','Limited range of motion','Muscle spasm','Guarding','Radiating pain','Flare-ups','Functional loss during flare-ups','Impact on daily activities'],
 'Range of motion is THE critical measurement. The examiner will measure your flexion, extension, lateral flexion, and rotation. Do NOT push through pain to show toughness — stop at the point where pain begins. Describe your WORST flare-ups: "During flare-ups I can barely bend to put on socks, which happens 2-3 times per month and lasts 3-5 days." Mention if you use assistive devices (back brace, cane). Describe how pain affects work: can you sit for 8 hours? Stand? Lift? Mention ANY incapacitating episodes that kept you in bed.',
 'Pushing through pain during range of motion testing — the examiner measures where you stop, not where your bones stop. Not mentioning flare-ups and their frequency/severity/duration. Not describing functional loss DURING flare-ups (per DeLuca factors). Saying "it hurts but I push through" instead of describing actual limitations. Not mentioning morning stiffness, difficulty sleeping, or medication use. Arriving at the exam after taking pain medication — the exam should reflect your typical pain level.'),

('Cervical strain', 'DBQ 21-0960M-13',
 ARRAY['Neck pain','Limited rotation/flexion','Muscle spasm','Radiating pain to arms','Headaches from neck','Guarding','Flare-ups','Numbness/tingling in arms'],
 'Same range of motion principles as lumbar — stop where pain begins. Cervical ratings use different ROM thresholds than lumbar. Describe radiculopathy symptoms (pain, numbness, tingling into arms) separately — they get their own rating. Mention headaches that originate from neck strain. Describe how neck limitation affects driving (checking blind spots), working at a computer, sleeping position. Quantify flare-ups with frequency, duration, and specific limitations during flare-ups.',
 'Same mistakes as lumbar — pushing through pain during ROM testing. Not separately claiming radiculopathy if you have arm symptoms. Not mentioning cervicogenic headaches. Not describing functional impact on driving, computer work, or sleeping. Forgetting to mention that turning your head is limited — this affects driving safety and work.'),

('Limitation of flexion — knee', 'DBQ 21-0960M-9',
 ARRAY['Pain on flexion','Limited range of motion','Crepitus','Swelling','Instability','Locking','Giving way','Impact on walking/stairs'],
 'Knee ratings depend on specific ROM measurements. Flexion limited to 45°=10%, 30°=20%, 15°=30%. Do NOT force your knee beyond where pain starts. Describe instability separately — it gets its own rating under DC 5257 IN ADDITION to limitation of motion. Mention locking episodes, giving way, and effusion (swelling). Describe functional impact: difficulty with stairs, squatting, kneeling, prolonged walking. If you wear a brace, bring it and explain when/why you use it.',
 'Pushing through pain to demonstrate full range of motion. Not mentioning instability — this is a SEPARATE rating on top of limitation of motion (you can get both). Not describing weight-bearing pain vs. non-weight-bearing. Forgetting to mention flare-ups that further limit motion. Not bringing or mentioning knee brace use. Not describing how knee problems affect daily activities and employment.'),

('Knee instability', 'DBQ 21-0960M-9',
 ARRAY['Giving way episodes','Subluxation','Need for knee brace','Falls from instability','Difficulty on uneven ground','Swelling after activity','Joint locking','Impact on employment'],
 'Instability is rated separately from limitation of motion — make sure both are evaluated. Describe specific giving-way episodes: "My knee buckled 3 times last month while walking." Bring your knee brace to the exam. Describe falls or near-falls. The examiner will perform Lachman''s test, anterior/posterior drawer test, and valgus/varus stress tests — do not resist or guard, let the examiner feel the laxity. Describe impact on work: "I can''t work on ladders or uneven surfaces."',
 'Not mentioning instability because the examiner only tested range of motion. Not bringing a knee brace. Tensing leg muscles during stability testing (masks the instability). Not reporting falls or near-falls from the knee giving way. Not explaining that instability and limitation of motion are separately ratable conditions.'),

('Tinnitus', 'DBQ 21-0960N-3',
 ARRAY['Ringing in ears','Buzzing/hissing sounds','Difficulty hearing in noisy environments','Sleep disruption from ringing','Difficulty concentrating','Impact on communication','Bilateral vs unilateral','Constant vs intermittent'],
 'Tinnitus is rated at a flat 10% regardless of severity or whether it''s in one or both ears. The key is establishing service connection. Describe your noise exposure in detail: weapons fired, equipment operated, blast events, flight line exposure. Describe how tinnitus affects daily life: difficulty sleeping, concentrating, hearing conversations. If you also have hearing loss, make sure BOTH conditions are claimed separately. Bring buddy statements from people who served with you confirming noise exposure.',
 'Not filing for hearing loss alongside tinnitus — they should always be filed together. Not describing the specific noise exposure events in service. Saying tinnitus is "not that bad" — even mild tinnitus gets 10%. Not connecting tinnitus to specific in-service noise events. Not getting a current audiology exam before the C&P.'),

('Hearing loss', 'DBQ 21-0960N-3',
 ARRAY['Difficulty hearing speech','Need for repetition','Difficulty in noisy environments','TV/phone volume increased','Difficulty hearing high-pitched sounds','Impact on work communication','Need for hearing aids','Tinnitus association'],
 'Hearing loss is rated based on audiometric test results using Tables VI and VII in 38 CFR 4.85. Do NOT wear hearing aids during the exam. Before the exam, avoid loud noise exposure for 24 hours. The exam includes pure tone audiometry and Maryland CNC word recognition testing. Describe your worst hearing situations: "I can''t hear my wife from another room, I miss radio calls at work, I have to face people to understand them." Describe occupational impact.',
 'Wearing hearing aids to the exam — the exam tests UNAIDED hearing. Getting a hearing test right after noise exposure (temporarily inflated thresholds look better, not worse). Not describing functional impact on work and daily life. Not filing tinnitus as a separate condition. Not describing in-service noise exposure in detail on the claim form.'),

('Hypertension', 'DBQ 21-0960A-2',
 ARRAY['Elevated systolic pressure','Elevated diastolic pressure','Headaches from blood pressure','Dizziness','Vision changes','Medication requirements','End-organ damage','Impact on activity'],
 'Hypertension ratings depend on blood pressure readings: 10% requires diastolic predominantly 100+ or systolic predominantly 160+ or continuous medication. 20% requires diastolic predominantly 110+ or systolic predominantly 200+. Keep a blood pressure log for 30 days before the exam showing your readings. Take readings at the same time daily. Do NOT take your blood pressure medication the morning of the exam — you want the exam to show your uncontrolled readings. Bring your medication list.',
 'Taking blood pressure medication before the exam — the readings will be artificially low. Not keeping a blood pressure log. Not mentioning all medications and doses. Having a "white coat" reading that''s lower than usual — bring your home readings to counter this. Not connecting hypertension to a service-connected condition (PTSD, sleep apnea, diabetes) for secondary service connection.'),

('Migraines', 'DBQ 21-0960C-8',
 ARRAY['Headache frequency','Duration of attacks','Prostrating nature','Nausea/vomiting','Sensitivity to light','Sensitivity to sound','Aura symptoms','Economic impact'],
 'The word "PROSTRATING" is critical — it means you must stop what you''re doing and lie down. 10% = prostrating attacks averaging once every 2 months. 30% = prostrating attacks once per month. 50% = very frequent completely prostrating and prolonged attacks productive of severe economic inadaptability. Keep a headache diary for 3+ months before the exam. Record: date, time started, duration, severity 1-10, whether you had to lie down, whether you missed work. Bring this diary to the exam.',
 'Not using the word "prostrating" or not explaining what it means for your functioning. Not keeping a headache diary. Saying headaches are "manageable" when they actually force you to lie down. Not connecting migraines to TBI if you have a TBI history. Not describing economic impact — missed work, lost jobs, reduced hours. Not mentioning medication side effects.'),

('Radiculopathy — lower extremity', 'DBQ 21-0960C-2',
 ARRAY['Radiating pain from back to leg','Numbness in leg/foot','Tingling/pins and needles','Muscle weakness','Decreased reflexes','Difficulty walking','Foot drop symptoms','Impact on sitting/standing'],
 'Radiculopathy is rated SEPARATELY from the back condition — each affected extremity gets its own rating. Describe exactly where the pain travels: "Pain shoots from my lower back through my left buttock, down the back of my left thigh, into my calf and foot." Mention numbness, tingling, and weakness. If you have an MRI showing disc herniation or nerve compression, bring it. Describe impact: "I can''t sit for more than 20 minutes without leg numbness." Get an EMG/nerve conduction study before the exam if possible.',
 'Not claiming radiculopathy separately from the back condition — it''s a separate rating. Not getting an MRI or EMG study. Describing pain vaguely ("my leg hurts") instead of tracing the nerve path. Not mentioning both legs if both are affected — each extremity is rated separately. Not describing functional limitations caused specifically by the leg symptoms (as opposed to back pain).'),

('Radiculopathy — upper extremity', 'DBQ 21-0960C-2',
 ARRAY['Radiating pain from neck to arm','Numbness in arm/hand','Tingling/pins and needles','Grip weakness','Decreased reflexes','Difficulty with fine motor tasks','Dropping objects','Impact on work tasks'],
 'Same principles as lower extremity radiculopathy — rated separately from neck condition. Dominant vs non-dominant arm affects the rating percentage. Describe the nerve path: "Pain radiates from my neck through my shoulder, down my right arm to my fingers." Mention grip weakness, difficulty with buttons, dropping things. Get cervical MRI and EMG if possible. Describe occupational impact: "I drop tools, can''t type for more than 15 minutes, have difficulty gripping a steering wheel."',
 'Not claiming separately from cervical condition. Not specifying dominant vs non-dominant arm. Not getting diagnostic studies (MRI, EMG). Vague pain descriptions. Not describing how hand/arm weakness affects work and daily tasks.'),

('Peripheral neuropathy — lower extremity', 'DBQ 21-0960C-2',
 ARRAY['Numbness in feet/legs','Burning pain','Tingling/pins and needles','Balance problems','Difficulty walking','Decreased sensation','Muscle weakness','Impact on daily activities'],
 'Each extremity is rated separately. Describe symptoms in EACH foot/leg individually. Mention if you stumble or fall due to loss of sensation. Describe burning pain, especially at night. If diabetic, make sure neuropathy is linked as secondary to diabetes. Mention if you can''t feel temperature changes or injuries in your feet. Describe impact on driving (can you feel the pedals?), walking, and balance. Get nerve conduction studies before the exam.',
 'Not claiming each extremity separately. Not getting nerve conduction study/EMG. Not connecting to diabetes or other service-connected cause. Describing symptoms generally instead of extremity-by-extremity. Not mentioning falls, burns, or injuries from decreased sensation. Not describing impact on driving and employment.'),

('Peripheral neuropathy — upper extremity', 'DBQ 21-0960C-2',
 ARRAY['Numbness in hands/fingers','Tingling','Burning pain','Grip weakness','Difficulty with fine motor','Dropping objects','Temperature sensitivity','Impact on work tasks'],
 'Rate each hand/arm separately. Dominant hand gets a higher rating. Describe grip weakness specifically: "I drop coffee cups, can''t button shirts, have difficulty writing." Mention if typing is difficult — this is a major occupational impairment. Describe tingling and numbness patterns. Get nerve conduction studies. Connect to diabetes or other service-connected condition.',
 'Not claiming each extremity separately. Not identifying dominant vs non-dominant hand. Not connecting to underlying service-connected condition. Not getting electrodiagnostic studies. Not describing specific fine motor task difficulties.'),

('GERD / Hiatal hernia', 'DBQ 21-0960G-3',
 ARRAY['Heartburn/pyrosis','Regurgitation','Difficulty swallowing','Substernal pain','Arm/shoulder pain from reflux','Nausea','Weight loss','Impact on diet/sleep'],
 'GERD is rated at 10%, 30%, or 60%. The 30% rating requires: persistently recurrent epigastric distress with dysphagia (difficulty swallowing), pyrosis (heartburn), and regurgitation, accompanied by substernal or arm/shoulder pain, productive of considerable impairment of health. Describe ALL symptoms — not just heartburn. Mention regurgitation episodes, difficulty swallowing, chest pain. Describe dietary restrictions. Describe sleep disruption from reflux. Mention ALL medications including PPIs and antacids and their side effects.',
 'Only mentioning heartburn and omitting dysphagia, regurgitation, and substernal pain — you need multiple symptoms for higher ratings. Not describing impairment of health. Not connecting GERD to PTSD medications (SSRIs cause GI issues) for secondary service connection. Not mentioning weight changes or dietary limitations.'),

('Erectile dysfunction', 'DBQ 21-0960J-1',
 ARRAY['Loss of erectile power','Inability to achieve erection','Inability to maintain erection','Deformity of penis','Impact on relationship','Medication for ED','Connection to service-connected conditions','Psychological impact'],
 'ED is rated at 0% with Special Monthly Compensation (SMC-K) adding ~$131/month — this is automatic when ED is service-connected. A 20% rating requires DEFORMITY of the penis in addition to loss of erectile power. The key is establishing service connection: secondary to PTSD medications, diabetes, hypertension, spinal conditions, or TBI. Any physician can diagnose ED — a urological exam is not always required. Document which service-connected condition or medication causes the ED.',
 'Not filing for ED because of embarrassment — it''s one of the most under-claimed conditions. Not connecting ED to service-connected conditions or their medications. Not knowing about SMC-K — even at 0% you get extra monthly compensation. Not mentioning which specific medications cause the ED (SSRIs, blood pressure meds, pain medications).'),

('Flat feet (pes planus)', 'DBQ 21-0960M-6',
 ARRAY['Pain on manipulation and use','Arch collapse visible','Inward bowing of Achilles tendon','Swelling on use','Callosities','Pronation','Need for orthotics','Impact on standing/walking'],
 'Flat feet ratings: 10% moderate (weight-bearing line over great toe, pain on manipulation), 30% severe (marked deformity, accentuated pain, swelling, callosities), 50% pronounced (extreme tenderness, marked inward displacement, severe spasm of Achilles, not improved by orthotics). Describe pain DURING the exam — don''t hide it. Show the examiner your calluses, arch collapse, and Achilles tendon bowing. If orthotics don''t help, say so explicitly — "pronounced" requires that the condition is NOT improved by orthopedic shoes/appliances. Stand on your feet for the exam to show the weight-bearing deformity.',
 'Wearing arch supports or orthotics to the exam that mask the deformity. Not showing the examiner the weight-bearing appearance of the feet. Saying orthotics help when they actually don''t — "not improved by appliances" is required for 50%. Not describing callosities, swelling after use, or Achilles tendon abnormality. Not connecting flat feet to secondary conditions (knees, hips, back).'),

('Shoulder — limitation of motion', 'DBQ 21-0960M-15',
 ARRAY['Pain on overhead motion','Limited range of motion','Difficulty reaching','Weakness','Guarding','Flare-ups','Impact on dressing/grooming','Need for assistance'],
 'Shoulder ratings depend on arm motion: at shoulder level (90°)=20%, midway between side and shoulder=30% (non-dominant), 25° from side=40% (non-dominant). Dominant arm gets higher ratings. Do NOT raise your arm above where pain begins. Describe functional limitations: "I can''t reach overhead cabinets, put on a jacket, or wash my hair without help." Describe flare-ups with frequency and additional limitation. If you have rotator cuff tear, mention it — additional pathology may warrant separate ratings.',
 'Raising arm above painful range to "show effort." Not specifying dominant vs non-dominant arm. Not describing functional limitations during flare-ups. Not claiming instability or impingement as separate issues. Not mentioning that you need help with dressing, grooming, or overhead tasks.'),

('Hip — limitation of motion', 'DBQ 21-0960M-5',
 ARRAY['Pain on flexion','Limited range of motion','Groin pain','Difficulty with stairs','Limping/antalgic gait','Difficulty putting on shoes/socks','Stiffness after sitting','Impact on walking distance'],
 'Hip flexion ratings: 45°=10%, 30°=20%, 20°=30%, 10°=40%. Also consider rotation and abduction limitations which are rated under DC 5253. Describe difficulty with everyday tasks: getting in/out of car, climbing stairs, putting on shoes and socks, getting up from chairs. Mention gait changes — if you limp, that''s objective evidence. Describe pain location specifically (groin, lateral hip, buttock). If hip problems are secondary to knee or back conditions, establish that connection.',
 'Not describing gait abnormality. Not mentioning limitation of rotation and abduction — these are separately ratable. Pushing through pain during ROM testing. Not connecting hip condition to service-connected knee or back conditions as secondary. Not describing impact on sitting tolerance and driving.'),

('Diabetes mellitus type 2', 'DBQ 21-0960E-1',
 ARRAY['Insulin requirements','Dietary restrictions','Activity regulation','Hypoglycemic episodes','Ketoacidosis episodes','Hospitalization frequency','Diabetic care provider visits','Complications'],
 'Diabetes ratings: 10% (diet only), 20% (insulin or oral agent + diet), 40% (insulin + diet + regulation of activities), 60% and 100% require hospitalizations and/or diabetic care visits at specific frequencies. "Regulation of activities" means a DOCTOR has told you to avoid strenuous activity — get this in writing. List ALL complications separately: neuropathy, retinopathy, nephropathy, ED — each gets its own secondary rating. Bring your A1C results, medication list, and documentation of any activity restrictions from your provider.',
 'Not having a doctor''s note restricting activities (required for 40%). Not claiming every diabetic complication separately. Not mentioning frequency of diabetic care visits. Not bringing A1C lab results. Not connecting diabetes to service (Agent Orange presumptive for Vietnam vets, or secondary to conditions/medications). Not documenting hypoglycemic episodes.'),

('Asthma', 'DBQ 21-0960L-1',
 ARRAY['FEV-1 results','FEV-1/FVC ratio','Frequency of exacerbations','Medication requirements','Emergency room visits','Hospitalization','Exercise limitation','Impact on work'],
 'Asthma is rated primarily on pulmonary function tests (PFTs) and medication requirements. Get PFTs done BEFORE the exam — the C&P examiner may not order them. Do NOT use your inhaler before the PFT test — the test should show your baseline lung function. Describe frequency of attacks, ER visits, and courses of oral steroids (prednisone). If you use daily inhalational therapy, document it. Describe how asthma limits physical activity and work.',
 'Using rescue inhaler before PFT testing — this artificially improves your numbers. Not getting PFTs before the C&P exam. Not documenting courses of systemic corticosteroids (prednisone) — this is key for 60% rating. Not describing exacerbation frequency. Not connecting asthma to burn pit exposure for PACT Act presumptive.'),

('Rhinitis / sinusitis', 'DBQ 21-0960L-2',
 ARRAY['Nasal obstruction percentage','Polyps presence','Headaches from sinuses','Purulent discharge','Pain/tenderness','Incapacitating episodes','Antibiotic courses','Impact on breathing/sleep'],
 'Rhinitis: 10% = >50% obstruction both sides or complete one side. 30% = polyps present. For sinusitis: count incapacitating episodes (requiring bed rest and antibiotics) and non-incapacitating episodes per year. Describe obstruction severity — do you breathe through your mouth? Does it affect sleep? Describe headaches, facial pain, and purulent discharge. Count antibiotic courses in the past year. If post-9/11, claim under PACT Act presumptive for burn pit exposure.',
 'Not knowing whether you have polyps (get a nasal endoscopy before the exam). Not counting sinus infections/antibiotic courses over the past year. Not describing nasal obstruction severity. Not connecting to sleep apnea as a secondary condition. Not claiming PACT Act presumptive if eligible.'),

('Dermatitis / eczema', 'DBQ 21-0960F-1',
 ARRAY['Percentage of body affected','Percentage of exposed areas','Topical medication use','Systemic medication use','Corticosteroid courses','Immunosuppressive therapy','Scarring','Impact on daily life'],
 'Skin ratings depend on two things: percentage of body affected and medication requirements. 10% = 5-20% of body OR intermittent systemic therapy <6 weeks. 30% = 20-40% of body OR systemic therapy ≥6 weeks. 60% = >40% of body OR constant systemic therapy. Have your dermatologist document the MAXIMUM extent of your condition during flare-ups, not just current extent. If you use topical steroids, systemic steroids, or immunosuppressants, document the frequency and duration. Take photos during flare-ups.',
 'Going to the exam during a period of remission when skin looks clear. Not documenting flare-up extent with photos. Not knowing what percentage of body is affected. Not classifying topical steroids as "systemic therapy" when used over large body areas. Not connecting skin conditions to burn pit/toxic exposure. Not mentioning that treatment is constant or near-constant.'),

('Scars — painful or unstable', 'DBQ 21-0960F-2',
 ARRAY['Pain on examination','Instability (skin breakdown)','Number of scars','Area of each scar','Limitation of function','Adherence to underlying tissue','Texture irregularity','Impact on daily life'],
 'Painful scars: 10% = 1-2 scars, 20% = 3-4 scars, 30% = 5+ scars. Each scar can also be rated for limitation of function of the affected body part SEPARATELY. Describe pain: constant vs. touch-sensitive. If scars limit motion (e.g., across a joint), that limitation gets its own rating. Show the examiner every scar — including surgical scars from service-connected surgeries. If scars are on the head/face/neck, disfigurement ratings under DC 7800 can be significant.',
 'Not showing all scars to the examiner. Not mentioning pain — the examiner may not ask about each scar individually. Not knowing that surgical scars from VA surgery for service-connected conditions are separately ratable. Not mentioning limitation of function caused by scarring. Not claiming facial/neck scars under the disfigurement criteria.'),

('Chronic fatigue syndrome', 'DBQ 21-0960N-1',
 ARRAY['Debilitating fatigue','Cognitive impairment','Unrefreshing sleep','Muscle pain','Joint pain','Headaches','Sore throat/lymph nodes','Exercise intolerance'],
 'CFS ratings depend on how much daily activity is restricted compared to pre-illness baseline: 10% (controlled by medication), 20% (<25% restriction OR <2 weeks incapacitating/year), 40% (50-75% restriction OR 2-4 weeks), 60% (<50% of pre-illness OR 4-6 weeks), 100% (almost complete restriction OR ≥6 weeks). Describe your pre-service/pre-illness activity level vs. now. Quantify: "I used to exercise 5x/week, now I can barely walk to the mailbox." Track incapacitating episodes (days you cannot get out of bed).',
 'Not having a definitive CFS diagnosis (requires specific diagnostic criteria). Not tracking incapacitating episodes. Not describing pre-illness activity baseline for comparison. Not mentioning all associated symptoms. Saying "I''m just tired" instead of describing debilitating fatigue that doesn''t improve with rest.'),

('Fibromyalgia', 'DBQ 21-0960M-3',
 ARRAY['Widespread pain','Tender points','Fatigue','Sleep disturbance','Stiffness','Paresthesias','Headaches','IBS symptoms'],
 'Fibromyalgia ratings: 10% (continuous medication required), 20% (episodic, symptoms present >1/3 of time), 40% (constant/near-constant, refractory to therapy). The key phrase is "refractory to therapy" for 40% — meaning treatment has been tried but symptoms persist. Document all medications tried and failed. Describe how symptoms wax and wane. Mention every associated symptom: IBS, depression, anxiety, headaches, Raynaud''s-like symptoms. Quantify: what percentage of days do you have significant symptoms?',
 'Not documenting failed treatment attempts (needed for "refractory to therapy"). Not mentioning all associated symptoms. Not claiming Gulf War presumptive if eligible. Describing symptoms as episodic when they''re actually present more than one-third of the time. Not connecting fibromyalgia to service.'),

('IBS (Irritable bowel syndrome)', 'DBQ 21-0960G-6',
 ARRAY['Diarrhea frequency','Constipation','Alternating diarrhea/constipation','Abdominal distress','Abdominal pain','Bloating','Urgency','Impact on work/travel'],
 'IBS ratings: 0% mild (occasional episodes), 10% moderate (frequent episodes), 30% severe (diarrhea or alternating diarrhea/constipation with more or less constant abdominal distress). Describe frequency: how many episodes per day/week? Describe urgency — do you need to be near a bathroom? Describe impact on work: missed days, inability to travel, need for bathroom proximity. If secondary to PTSD or PTSD medications, establish that connection.',
 'Downplaying frequency and severity. Not describing "constant abdominal distress" clearly enough for 30% rating. Not connecting to PTSD or medications. Not describing impact on employment and social activities. Not mentioning dietary restrictions necessitated by IBS.'),

('Varicose veins', 'DBQ 21-0960A-5',
 ARRAY['Edema','Aching/fatigue in legs','Stasis pigmentation','Eczema','Ulceration','Need for compression hosiery','Impact on standing/walking','Elevation needed'],
 'Varicose vein ratings escalate with persistent symptoms: 10% (intermittent edema, aching after standing, relieved by elevation/compression), 20% (persistent edema not fully relieved by elevation), 40% (persistent edema + stasis pigmentation or eczema, with or without intermittent ulceration), 60% (persistent edema + stasis pigmentation/eczema + persistent ulceration), 100% (massive board-like edema with constant pain). Each leg is rated separately. Describe symptoms in each leg individually. Bring compression stockings to the exam.',
 'Not claiming each leg separately. Not describing edema persistence (intermittent vs. persistent vs. constant). Not mentioning skin changes (stasis dermatitis, pigmentation). Not describing that elevation does not fully relieve the edema. Not wearing shorts to show the veins to the examiner.'),

('Degenerative arthritis', 'DBQ 21-0960M-1',
 ARRAY['Joint pain','Stiffness','Swelling','Crepitus','Limited range of motion','X-ray evidence','Flare-ups','Impact on daily activities'],
 'Arthritis is rated under DC 5003 based on limitation of motion of the affected joint. Even if motion is "full" by measurement, if it''s PAINFUL, you get at least 10% per joint under 38 CFR 4.59 (painful motion doctrine). Make sure the examiner documents where pain begins during ROM testing. Each affected joint can be rated separately. Bring X-rays or MRI reports showing arthritis. Describe morning stiffness duration, flare-up frequency, and functional limitations during flare-ups.',
 'Not getting X-rays showing arthritis before the exam. Not stopping at the point of pain during ROM testing. Not claiming each arthritic joint separately. Not knowing about the painful motion doctrine (38 CFR 4.59) — even non-compensable limitation of motion with pain gets 10%. Not describing flare-ups.'),

('Ankle — limited motion', 'DBQ 21-0960M-2',
 ARRAY['Pain on motion','Limited dorsiflexion','Limited plantar flexion','Swelling','Instability','Difficulty walking on uneven surfaces','Need for ankle brace','Impact on standing/walking'],
 'Ankle ratings: 10% moderate limitation, 20% marked limitation. Describe pain on weight-bearing specifically. Mention instability — ankle gives way. If you use a brace, bring it. Describe difficulty on stairs, uneven ground, and prolonged walking. If ankle condition is secondary to knee or foot conditions, establish that connection. Mention flare-ups and additional limitation during flare-ups.',
 'Not describing the difference between weight-bearing and non-weight-bearing pain. Not mentioning instability separately. Not bringing ankle brace. Not connecting to related knee/foot conditions. Pushing through pain during dorsiflexion/plantar flexion testing.'),

('Temporomandibular disorder (TMJ)', 'DBQ 21-0960M-11',
 ARRAY['Limited jaw opening','Jaw pain','Clicking/popping','Locking','Difficulty chewing','Headaches from TMJ','Ear pain','Impact on eating/speaking'],
 'TMJ is rated on inter-incisal range (how wide you can open your mouth): 31-40mm=10%, 21-30mm=20%, 11-20mm=30%, 0-10mm=40%. Also rated on lateral excursion: 0-4mm=10%. Describe pain on opening, clicking, and locking episodes. Mention dietary limitations (can you eat solid food?). Describe headaches originating from TMJ. If TMJ is secondary to dental trauma in service or TBI, establish that connection. Do NOT force your jaw open during the exam — stop at pain.',
 'Forcing jaw open beyond painful range during measurement. Not mentioning locking episodes. Not describing dietary limitations. Not connecting to in-service dental trauma or TBI. Not mentioning that TMJ headaches are separate from other headache conditions.'),

('Gastritis / duodenal ulcer', 'DBQ 21-0960G-1',
 ARRAY['Epigastric pain','Nausea/vomiting','Hematemesis','Melena','Weight loss','Anemia','Recurrent symptoms','Medication requirements'],
 'Describe frequency and severity of episodes. Mention any vomiting blood (hematemesis) or black stools (melena) — these are critical for higher ratings. Document weight loss. Bring lab results showing anemia if applicable. Describe impact on diet and appetite. If secondary to PTSD medications or NSAIDs for service-connected pain, establish that connection. Describe how symptoms affect your ability to eat normally and maintain weight.',
 'Not mentioning hematemesis or melena. Not documenting weight loss. Not bringing anemia lab results. Not connecting to NSAID use for service-connected pain. Not describing frequency of symptom recurrence.'),

('Carpal tunnel syndrome', 'DBQ 21-0960C-2',
 ARRAY['Numbness in thumb/index/middle fingers','Tingling','Pain radiating up forearm','Grip weakness','Dropping objects','Wrist pain','Night symptoms','Impact on typing/writing'],
 'Carpal tunnel is rated as median nerve impairment: mild=10%, moderate=30% (non-dominant) or 30% (dominant), severe=50% (non-dominant) or 50% (dominant). Each wrist is rated separately. Dominant hand gets higher ratings. Get nerve conduction studies before the exam — objective evidence is critical. Describe functional limitations: difficulty typing, writing, gripping tools, opening jars. Mention night symptoms (waking with numb hands). Describe occupational impact specifically.',
 'Not getting nerve conduction studies. Not claiming each wrist separately. Not identifying dominant hand. Describing symptoms as "minor" when they actually impair work function. Not connecting to military duties (repetitive use, heavy equipment vibration). Not describing night symptoms.'),

('Burn pit exposure — respiratory', 'DBQ 21-0960L-1',
 ARRAY['Chronic cough','Shortness of breath','Wheezing','Chest tightness','Reduced exercise tolerance','PFT results','Frequency of exacerbations','Medication requirements'],
 'Under the PACT Act (2022), respiratory conditions are presumptive for veterans who served in covered locations after 9/11 — NO nexus letter needed. Get pulmonary function tests (PFTs) before the C&P exam. Do NOT use inhalers before PFTs. Describe symptoms in detail: chronic cough, shortness of breath on exertion (at what level of activity?), wheezing. Document all respiratory medications. Describe impact on exercise tolerance: "I can''t walk more than one block without stopping." Register in the VA Burn Pit Registry if you haven''t already.',
 'Not registering in the VA Burn Pit Registry. Using inhalers before PFTs. Not getting PFTs before the C&P exam. Not claiming PACT Act presumptive status. Not describing the burn pit exposure location and duration in detail on the claim form. Not describing current functional limitations from respiratory symptoms.'),

('Vestibular disorder / vertigo', 'DBQ 21-0960N-4',
 ARRAY['Dizziness episodes','Vertigo attacks','Balance problems','Nausea from dizziness','Staggering gait','Falls','Impact on driving','Impact on work'],
 'Vestibular disorders: 10% occasional dizziness, 30% dizziness and occasional staggering. If secondary to TBI or ear conditions, establish that connection. Describe frequency of vertigo episodes, their duration, and triggers. Mention falls or near-falls. Describe impact on driving safety. Mention nausea/vomiting during episodes. The examiner should perform Dix-Hallpike and other vestibular tests — do not try to suppress dizziness during testing.',
 'Not connecting to TBI, ear conditions, or medications. Suppressing dizziness during vestibular testing. Not describing falls or near-falls. Not mentioning impact on driving. Not quantifying episode frequency and duration.');
