-- Seed: 120 most commonly rated VA diagnostic codes from 38 CFR Part 4
-- Run in Supabase SQL Editor AFTER running schema.sql

INSERT INTO diagnostic_codes (code, condition_name, body_system, rating_0_criteria, rating_10_criteria, rating_20_criteria, rating_30_criteria, rating_40_criteria, rating_50_criteria, rating_60_criteria, rating_70_criteria, rating_80_criteria, rating_100_criteria, cfr_citation) VALUES

-- ═══════════════════════════════════════════
-- MENTAL DISORDERS (General Rating Formula: 38 CFR 4.130)
-- ═══════════════════════════════════════════

('9411', 'PTSD', 'Mental Disorders',
 'Diagnosed but symptoms not severe enough to interfere with occupational/social functioning, or symptoms controlled by medication',
 'Occupational and social impairment due to mild or transient symptoms which decrease work efficiency only during periods of significant stress, or symptoms controlled by continuous medication',
 'Occupational and social impairment with occasional decrease in work efficiency and intermittent periods of inability to perform occupational tasks due to such symptoms as depressed mood, anxiety, suspiciousness, panic attacks weekly or less often, chronic sleep impairment, mild memory loss',
 'Occupational and social impairment with occasional decrease in work efficiency and intermittent periods of inability to perform occupational tasks due to such symptoms as depressed mood, anxiety, suspiciousness, panic attacks weekly or less often, chronic sleep impairment, mild memory loss such as forgetting names, directions, recent events',
 NULL, -- 40% not used for mental disorders
 'Occupational and social impairment with reduced reliability and productivity due to such symptoms as flattened affect, circumstantial/circumlocutory/stereotyped speech, panic attacks more than once a week, difficulty understanding complex commands, impairment of short and long term memory, impaired judgment, impaired abstract thinking, disturbances of motivation and mood, difficulty in establishing and maintaining effective work and social relationships',
 NULL, -- 60% not used for mental disorders
 'Occupational and social impairment with deficiencies in most areas such as work, school, family relations, judgment, thinking, or mood due to such symptoms as suicidal ideation, obsessional rituals, speech intermittently illogical/obscure/irrelevant, near-continuous panic or depression affecting ability to function, impaired impulse control, spatial disorientation, neglect of personal appearance and hygiene, difficulty adapting to stressful circumstances, inability to establish and maintain effective relationships',
 NULL,
 'Total occupational and social impairment due to such symptoms as gross impairment in thought processes or communication, persistent delusions or hallucinations, grossly inappropriate behavior, persistent danger of hurting self or others, intermittent inability to perform activities of daily living, disorientation to time or place, memory loss for names of close relatives or own occupation or own name',
 '38 CFR § 4.130, DC 9411'),

('9434', 'Major depressive disorder', 'Mental Disorders',
 'Diagnosed but symptoms not severe enough to interfere with occupational/social functioning, or symptoms controlled by medication',
 'Occupational and social impairment due to mild or transient symptoms which decrease work efficiency only during periods of significant stress, or symptoms controlled by continuous medication',
 'Occupational and social impairment with occasional decrease in work efficiency and intermittent periods of inability to perform occupational tasks due to depressed mood, chronic sleep impairment, mild memory loss',
 'Occupational and social impairment with occasional decrease in work efficiency due to depressed mood, anxiety, chronic sleep impairment, mild memory loss such as forgetting names, directions, recent events',
 NULL,
 'Occupational and social impairment with reduced reliability and productivity due to flattened affect, panic attacks more than once a week, difficulty understanding complex commands, impaired memory and judgment, disturbances of motivation and mood, difficulty establishing effective relationships',
 NULL,
 'Occupational and social impairment with deficiencies in most areas due to suicidal ideation, near-continuous depression affecting ability to function, impaired impulse control, neglect of personal appearance, inability to establish and maintain effective relationships',
 NULL,
 'Total occupational and social impairment due to gross impairment in thought processes, persistent danger of hurting self or others, inability to perform activities of daily living, disorientation, severe memory loss',
 '38 CFR § 4.130, DC 9434'),

('9400', 'Generalized anxiety disorder', 'Mental Disorders',
 'Diagnosed but symptoms not severe enough to interfere with occupational/social functioning',
 'Mild or transient symptoms decreasing work efficiency only during significant stress',
 'Occasional decrease in work efficiency due to anxiety, suspiciousness, panic attacks weekly or less, chronic sleep impairment',
 'Occasional decrease in work efficiency due to anxiety, panic attacks weekly or less, chronic sleep impairment, mild memory loss',
 NULL,
 'Reduced reliability and productivity due to panic attacks more than once a week, impaired memory, disturbances of motivation and mood, difficulty in establishing effective relationships',
 NULL,
 'Deficiencies in most areas due to obsessional rituals, near-continuous panic or depression, impaired impulse control, spatial disorientation, inability to establish effective relationships',
 NULL,
 'Total occupational and social impairment due to persistent delusions/hallucinations, grossly inappropriate behavior, persistent danger of hurting self/others, disorientation',
 '38 CFR § 4.130, DC 9400'),

('9440', 'Chronic adjustment disorder', 'Mental Disorders',
 'Diagnosed but symptoms controlled or not severe enough to interfere with functioning',
 'Mild or transient symptoms decreasing work efficiency only during significant stress',
 'Occasional decrease in work efficiency due to depressed mood, anxiety, chronic sleep impairment',
 'Occasional decrease in work efficiency due to depressed mood, anxiety, chronic sleep impairment, mild memory loss',
 NULL,
 'Reduced reliability and productivity due to flattened affect, panic attacks, impaired judgment, difficulty establishing relationships',
 NULL,
 'Deficiencies in most areas due to suicidal ideation, near-continuous panic or depression, impaired impulse control, inability to maintain relationships',
 NULL,
 'Total occupational and social impairment',
 '38 CFR § 4.130, DC 9440'),

('8045', 'Traumatic brain injury', 'Mental Disorders',
 'Subjective complaints only — no objective evidence of cognitive impairment on testing',
 'Three or more subjective symptoms that mildly interfere with work, instrumental activities of daily living, or social relationships',
 'One or more neurocognitive impairments at level 1 (mildly impaired)',
 'One or more neurocognitive impairments at level 2 (moderately impaired)',
 'One or more neurocognitive impairments at level 3 (severely impaired, some independence maintained)',
 NULL, NULL,
 'One or more neurocognitive impairments at level 3 with major impact on most areas of functioning',
 NULL,
 'Total impairment — completely unable to function independently in any area',
 '38 CFR § 4.124a, DC 8045'),

('9435', 'Mood disorder due to general medical condition', 'Mental Disorders',
 'Diagnosed but symptoms controlled', 'Mild or transient symptoms', 'Occasional decrease in work efficiency',
 'Occasional decrease in work efficiency due to depressed mood, anxiety, chronic sleep impairment, mild memory loss',
 NULL,
 'Reduced reliability and productivity due to flattened affect, impaired judgment, difficulty establishing relationships',
 NULL,
 'Deficiencies in most areas due to suicidal ideation, near-continuous depression, inability to maintain relationships',
 NULL,
 'Total occupational and social impairment',
 '38 CFR § 4.130, DC 9435'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — SPINE
-- ═══════════════════════════════════════════

('5237', 'Lumbosacral strain', 'Musculoskeletal',
 'No compensable limitation of motion; normal range of motion with subjective complaints only',
 'Forward flexion greater than 60 degrees but not greater than 85 degrees, OR combined range of motion greater than 120 degrees but not greater than 235 degrees, OR muscle spasm/guarding/localized tenderness not resulting in abnormal gait or spinal contour',
 'Forward flexion greater than 30 degrees but not greater than 60 degrees, OR combined range of motion not greater than 120 degrees, OR muscle spasm or guarding severe enough to result in abnormal gait or abnormal spinal contour',
 'Forward flexion of 30 degrees or less, OR favorable ankylosis of the entire thoracolumbar spine',
 'Unfavorable ankylosis of the entire thoracolumbar spine',
 'Unfavorable ankylosis of the entire thoracolumbar spine',
 'Unfavorable ankylosis of the entire spine',
 NULL, NULL,
 'Unfavorable ankylosis of the entire spine with loss of use of lower extremities',
 '38 CFR § 4.71a, DC 5237'),

('5242', 'Degenerative arthritis of the spine', 'Musculoskeletal',
 'No compensable limitation of motion with X-ray evidence of involvement of 2+ major joints',
 'Forward flexion >60-85 degrees OR combined ROM >120-235 degrees OR muscle spasm/guarding/localized tenderness',
 'Forward flexion >30-60 degrees OR combined ROM ≤120 degrees OR muscle spasm/guarding causing abnormal gait or spinal contour',
 'Forward flexion 30 degrees or less OR favorable ankylosis of entire thoracolumbar spine',
 'Unfavorable ankylosis of the entire thoracolumbar spine',
 'Unfavorable ankylosis of the entire thoracolumbar spine', NULL, NULL, NULL,
 'Unfavorable ankylosis of the entire spine',
 '38 CFR § 4.71a, DC 5242'),

('5243', 'Intervertebral disc syndrome (IVDS)', 'Musculoskeletal',
 'No incapacitating episodes in past 12 months',
 'Incapacitating episodes having a total duration of at least 1 week but less than 2 weeks during the past 12 months',
 'Incapacitating episodes having a total duration of at least 2 weeks but less than 4 weeks during the past 12 months',
 'Incapacitating episodes having a total duration of at least 4 weeks but less than 6 weeks during the past 12 months',
 'Incapacitating episodes having a total duration of at least 4 weeks but less than 6 weeks',
 NULL,
 'Incapacitating episodes having a total duration of at least 6 weeks during the past 12 months',
 NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5243'),

('5238', 'Spinal stenosis', 'Musculoskeletal',
 'No compensable limitation of motion',
 'Forward flexion >60-85 degrees OR combined ROM >120-235 degrees OR localized tenderness',
 'Forward flexion >30-60 degrees OR combined ROM ≤120 degrees OR muscle spasm causing abnormal gait',
 'Forward flexion 30 degrees or less OR favorable ankylosis',
 'Unfavorable ankylosis of entire thoracolumbar spine',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5238'),

('5241', 'Spinal fusion', 'Musculoskeletal',
 NULL,
 'Forward flexion >60-85 degrees post-fusion',
 'Forward flexion >30-60 degrees post-fusion OR combined ROM ≤120 degrees',
 'Forward flexion 30 degrees or less OR favorable ankylosis',
 'Unfavorable ankylosis of entire thoracolumbar spine',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5241'),

('5235', 'Vertebral fracture or dislocation', 'Musculoskeletal',
 NULL,
 'Forward flexion >60-85 degrees',
 'Forward flexion >30-60 degrees OR combined ROM ≤120 degrees',
 'Forward flexion 30 degrees or less OR favorable ankylosis',
 'Unfavorable ankylosis of entire thoracolumbar spine',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5235'),

('5236', 'Sacroiliac injury/weakness', 'Musculoskeletal',
 NULL,
 'Forward flexion >60-85 degrees OR localized tenderness',
 'Forward flexion >30-60 degrees OR muscle spasm causing abnormal gait',
 'Forward flexion 30 degrees or less OR favorable ankylosis',
 'Unfavorable ankylosis of entire thoracolumbar spine',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5236'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — CERVICAL
-- ═══════════════════════════════════════════

('5237-C', 'Cervical strain', 'Musculoskeletal',
 'No compensable limitation of motion',
 'Forward flexion greater than 30 degrees but not greater than 40 degrees, OR combined ROM greater than 170 degrees but not greater than 335 degrees, OR muscle spasm/guarding/localized tenderness',
 'Forward flexion greater than 15 degrees but not greater than 30 degrees, OR combined ROM not greater than 170 degrees, OR muscle spasm severe enough to result in abnormal gait or spinal contour',
 'Forward flexion of 15 degrees or less, OR favorable ankylosis of the entire cervical spine',
 'Unfavorable ankylosis of the entire cervical spine',
 NULL, NULL, NULL, NULL,
 'Unfavorable ankylosis of the entire spine',
 '38 CFR § 4.71a, DC 5237 (cervical)'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — KNEES
-- ═══════════════════════════════════════════

('5260', 'Limitation of flexion — knee', 'Musculoskeletal',
 'Flexion limited to 60 degrees (noncompensable)',
 'Flexion limited to 45 degrees',
 'Flexion limited to 30 degrees',
 'Flexion limited to 15 degrees',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5260'),

('5261', 'Limitation of extension — knee', 'Musculoskeletal',
 'Extension limited to 5 degrees (noncompensable)',
 'Extension limited to 10 degrees',
 'Extension limited to 15 degrees',
 'Extension limited to 20 degrees',
 'Extension limited to 30 degrees',
 'Extension limited to 45 degrees',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5261'),

('5257', 'Knee instability — recurrent subluxation or lateral instability', 'Musculoskeletal',
 NULL,
 'Slight recurrent subluxation or lateral instability',
 'Moderate recurrent subluxation or lateral instability',
 'Severe recurrent subluxation or lateral instability',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5257'),

('5258', 'Dislocated semilunar cartilage (meniscus) — knee', 'Musculoskeletal',
 NULL, NULL,
 'Dislocated semilunar cartilage with frequent episodes of locking, pain, and effusion into the joint',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5258'),

('5259', 'Removal of semilunar cartilage (meniscectomy) — knee', 'Musculoskeletal',
 NULL,
 'Symptomatic after removal of semilunar cartilage',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5259'),

('5003', 'Degenerative arthritis (general)', 'Musculoskeletal',
 'X-ray evidence of arthritis in 2+ major joints without compensable limitation of motion',
 'X-ray evidence with noncompensable limitation of motion, rated under appropriate diagnostic code with minimum 10%. Or: painful motion documented on exam, minimum 10%',
 'Incapacitating exacerbations occurring at least once a year',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5003'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — HIPS
-- ═══════════════════════════════════════════

('5252', 'Limitation of flexion — hip/thigh', 'Musculoskeletal',
 NULL,
 'Flexion limited to 45 degrees',
 'Flexion limited to 30 degrees',
 'Flexion limited to 20 degrees',
 'Flexion limited to 10 degrees',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5252'),

('5253', 'Limitation of rotation/abduction — hip/thigh', 'Musculoskeletal',
 NULL,
 'Limitation of rotation — cannot toe-out more than 15 degrees with affected leg',
 'Limitation of abduction — cannot cross legs OR limitation of abduction, motion lost beyond 10 degrees',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5253'),

('5255', 'Femur impairment — malunion or fracture', 'Musculoskeletal',
 NULL,
 'Malunion with slight knee or hip disability',
 'Malunion with moderate knee or hip disability',
 'Malunion with marked knee or hip disability',
 NULL, NULL,
 'Fracture of surgical neck, with false joint OR nonunion without loose motion, weight bearing preserved with aid of brace',
 NULL,
 'Fracture of shaft or anatomical neck with nonunion, with loose motion (spiral or oblique fracture)',
 NULL,
 '38 CFR § 4.71a, DC 5255'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — SHOULDERS
-- ═══════════════════════════════════════════

('5201', 'Limitation of arm motion — shoulder', 'Musculoskeletal',
 NULL, NULL,
 'Arm motion limited to shoulder level (90 degrees) — dominant or non-dominant',
 'Arm motion limited to midway between side and shoulder level (45-90 degrees) — non-dominant. Dominant arm: 30%',
 'Arm motion limited to 25 degrees from side — non-dominant. Dominant arm: 40%',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5201'),

('5200', 'Ankylosis of scapulohumeral articulation — shoulder', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Favorable ankylosis — abduction to 60 degrees, can reach mouth and head (non-dominant)',
 'Intermediate ankylosis between favorable and unfavorable (non-dominant)',
 'Unfavorable ankylosis — abduction limited to 25 degrees from side (non-dominant)',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5200'),

('5202', 'Humerus impairment — recurrent dislocation', 'Musculoskeletal',
 NULL, NULL,
 'Infrequent episodes of dislocation and guarding of movement only at shoulder level (non-dominant)',
 'Frequent episodes of dislocation and guarding of all arm movements (non-dominant)',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5202'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — ANKLES/FEET
-- ═══════════════════════════════════════════

('5271', 'Limited motion of ankle', 'Musculoskeletal',
 NULL,
 'Moderate limitation of motion of the ankle',
 'Marked limitation of motion of the ankle',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5271'),

('5276', 'Flatfoot, acquired (pes planus)', 'Musculoskeletal',
 'Mild — symptoms relieved by built-up shoe or arch support',
 'Moderate — weight-bearing line over or medial to great toe, inward bowing of the Achilles tendon, pain on manipulation and use of the feet (bilateral or unilateral)',
 NULL,
 'Severe — objective evidence of marked deformity (pronation, abduction), pain on manipulation and use accentuated, indication of swelling on use, characteristic callosities (bilateral)',
 NULL,
 'Pronounced — marked pronation, extreme tenderness of plantar surfaces of the feet, marked inward displacement and severe spasm of the Achilles tendon on manipulation, not improved by orthopedic shoes or appliances (bilateral)',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5276'),

('5284', 'Foot injuries, other', 'Musculoskeletal',
 NULL,
 'Moderate foot injury',
 'Moderately severe foot injury',
 'Severe foot injury',
 'Actual loss of use of the foot — 40% rating',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5284'),

('5278', 'Claw foot (pes cavus) — acquired', 'Musculoskeletal',
 NULL,
 'Great toe dorsiflexed, some limitation of dorsiflexion at ankle, definite tenderness under metatarsal heads (bilateral)',
 'All toes tending to dorsiflexion, limitation of dorsiflexion at ankle to right angle, shortened plantar fascia, marked tenderness (bilateral)',
 'Marked contraction of plantar fascia with dropped forefoot, all toes hammer toes, very painful callosities, marked varus deformity (bilateral)',
 NULL,
 'Marked contraction of plantar fascia with dropped forefoot, all toes hammer toes, very painful callosities, marked varus deformity (bilateral), not improved by surgery',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5278'),

('5279', 'Metatarsalgia, anterior (Morton''s disease)', 'Musculoskeletal',
 NULL,
 'Metatarsalgia, anterior (Morton''s disease), unilateral or bilateral',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5279'),

('5280', 'Hallux valgus', 'Musculoskeletal',
 NULL,
 'Operated with resection of metatarsal head, OR severe if equivalent to amputation of great toe',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5280'),

('5284-PF', 'Plantar fasciitis', 'Musculoskeletal',
 NULL,
 'Moderate — pain on use, responds to conservative treatment',
 'Moderately severe — persistent pain limiting prolonged standing/walking',
 'Severe — constant pain, significantly limits all weight-bearing activity',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5284 (analogous)'),

-- ═══════════════════════════════════════════
-- MUSCULOSKELETAL — ELBOW/WRIST/HAND
-- ═══════════════════════════════════════════

('5206', 'Forearm — limitation of flexion', 'Musculoskeletal',
 'Flexion limited to 110 degrees (noncompensable)',
 'Flexion limited to 100 degrees',
 'Flexion limited to 90 degrees',
 'Flexion limited to 70 degrees (non-dominant)',
 'Flexion limited to 55 degrees (non-dominant)',
 'Flexion limited to 45 degrees (non-dominant)',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5206'),

('5215', 'Wrist — limitation of motion', 'Musculoskeletal',
 NULL,
 'Dorsiflexion less than 15 degrees OR palmar flexion limited in line with forearm',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5215'),

-- ═══════════════════════════════════════════
-- CARDIOVASCULAR
-- ═══════════════════════════════════════════

('7101', 'Hypertension', 'Cardiovascular',
 'No compensable — diastolic pressure predominantly less than 100, systolic pressure predominantly less than 160',
 'Diastolic pressure predominantly 100 or more, OR systolic pressure predominantly 160 or more, OR minimum evaluation for individual with history of diastolic pressure predominantly 100 or more who requires continuous medication for control',
 'Diastolic pressure predominantly 110 or more, OR systolic pressure predominantly 200 or more',
 NULL,
 'Diastolic pressure predominantly 120 or more',
 NULL,
 'Diastolic pressure predominantly 130 or more',
 NULL, NULL, NULL,
 '38 CFR § 4.104, DC 7101'),

('7005', 'Arteriosclerotic heart disease (coronary artery disease)', 'Cardiovascular',
 NULL,
 'Workload of greater than 7 METs but not greater than 10 METs resulting in dyspnea, fatigue, angina, dizziness, or syncope, OR continuous medication required',
 NULL,
 'Workload of greater than 5 METs but not greater than 7 METs resulting in dyspnea, fatigue, angina, dizziness, or syncope, OR evidence of cardiac hypertrophy on ECG/echo/X-ray',
 NULL, NULL,
 'More than one episode of acute congestive heart failure in past year, OR workload of greater than 3 METs but not greater than 5 METs resulting in symptoms, OR left ventricular dysfunction with ejection fraction of 30-50%',
 NULL, NULL,
 'Chronic congestive heart failure, OR workload of 3 METs or less resulting in symptoms, OR left ventricular dysfunction with ejection fraction less than 30%',
 '38 CFR § 4.104, DC 7005'),

('7007', 'Hypertensive heart disease', 'Cardiovascular',
 NULL,
 'Workload >7-10 METs resulting in symptoms OR continuous medication required',
 NULL,
 'Workload >5-7 METs resulting in symptoms OR cardiac hypertrophy',
 NULL, NULL,
 'More than one episode of CHF in past year OR workload >3-5 METs OR EF 30-50%',
 NULL, NULL,
 'Chronic CHF OR workload ≤3 METs OR EF <30%',
 '38 CFR § 4.104, DC 7007'),

-- ═══════════════════════════════════════════
-- RESPIRATORY
-- ═══════════════════════════════════════════

('6847', 'Sleep apnea — obstructive', 'Respiratory',
 'Asymptomatic but with documented sleep disorder breathing',
 NULL, NULL,
 'Persistent daytime hypersomnolence',
 NULL,
 'Requires use of a breathing assistance device such as CPAP machine',
 NULL, NULL, NULL,
 'Chronic respiratory failure with carbon dioxide retention or cor pulmonale, OR requires tracheostomy',
 '38 CFR § 4.97, DC 6847'),

('6602', 'Asthma — bronchial', 'Respiratory',
 NULL,
 'FEV-1 of 71-80% predicted, OR FEV-1/FVC of 71-80%, OR intermittent inhalational or oral bronchodilator therapy',
 NULL,
 'FEV-1 of 56-70% predicted, OR FEV-1/FVC of 56-70%, OR daily inhalational or oral bronchodilator therapy, OR inhalational anti-inflammatory medication',
 NULL, NULL,
 'FEV-1 of 40-55% predicted, OR FEV-1/FVC of 40-55%, OR at least monthly visits to physician for exacerbations, OR intermittent (at least 3x/year) courses of systemic corticosteroids',
 NULL, NULL,
 'FEV-1 less than 40% predicted, OR FEV-1/FVC less than 40%, OR more than one attack per week with episodes of respiratory failure, OR requires daily use of systemic high-dose corticosteroids or immuno-suppressive medications',
 '38 CFR § 4.97, DC 6602'),

('6522', 'Allergic rhinitis', 'Respiratory',
 NULL,
 'Without polyps, but with greater than 50% obstruction of nasal passage on both sides or complete obstruction on one side',
 NULL,
 'With polyps',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.97, DC 6522'),

('6510', 'Chronic sinusitis — pansinusitis', 'Respiratory',
 'Detected by X-ray only with symptoms',
 'One or two incapacitating episodes per year of sinusitis requiring prolonged antibiotic treatment, OR three to six non-incapacitating episodes per year characterized by headaches, pain, and purulent discharge or crusting',
 NULL,
 'Three or more incapacitating episodes per year requiring prolonged antibiotic treatment, OR more than six non-incapacitating episodes per year',
 NULL,
 'Following radical surgery with chronic osteomyelitis, OR near constant sinusitis characterized by headaches, pain and tenderness of affected sinus, and purulent discharge or crusting after repeated surgeries',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.97, DC 6510-6514'),

('6600', 'Bronchitis — chronic', 'Respiratory',
 NULL,
 'FEV-1 of 71-80% predicted, OR FEV-1/FVC of 71-80%, OR DLCO 66-80% predicted',
 NULL,
 'FEV-1 of 56-70% predicted, OR FEV-1/FVC of 56-70%, OR DLCO 56-65% predicted',
 NULL, NULL,
 'FEV-1 of 40-55% predicted, OR FEV-1/FVC of 40-55%, OR DLCO 40-55% predicted, OR maximum oxygen consumption of 15-20 ml/kg/min',
 NULL, NULL,
 'FEV-1 <40%, OR FEV-1/FVC <40%, OR DLCO <40%, OR max O2 consumption <15 ml/kg/min, OR cor pulmonale, OR right ventricular hypertrophy, OR pulmonary hypertension, OR requires outpatient oxygen therapy',
 '38 CFR § 4.97, DC 6600'),

-- ═══════════════════════════════════════════
-- NEUROLOGICAL
-- ═══════════════════════════════════════════

('8100', 'Migraines', 'Neurological',
 'Less frequent attacks than for 10% rating',
 'Characteristic prostrating attacks averaging one in 2 months over last several months',
 NULL,
 'Characteristic prostrating attacks occurring on an average once a month over last several months',
 NULL,
 'Very frequent completely prostrating and prolonged attacks productive of severe economic inadaptability',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8100'),

('8520', 'Sciatic nerve — paralysis/incomplete', 'Neurological',
 NULL,
 'Mild incomplete paralysis of the sciatic nerve',
 'Moderate incomplete paralysis of the sciatic nerve',
 NULL,
 'Moderately severe incomplete paralysis of the sciatic nerve',
 NULL,
 'Severe incomplete paralysis with marked muscular atrophy',
 NULL,
 'Complete paralysis — foot dangles and drops, no active movement possible below knee, flexion of knee weakened or lost',
 NULL,
 '38 CFR § 4.124a, DC 8520'),

('8515', 'Median nerve — paralysis/incomplete', 'Neurological',
 NULL,
 'Mild incomplete paralysis (dominant or non-dominant)',
 NULL,
 'Moderate incomplete paralysis (non-dominant; dominant: 30%)',
 NULL,
 'Severe incomplete paralysis (non-dominant; dominant: 50%)',
 NULL,
 'Complete paralysis — hand inclined to ulnar side, thumb unable to be abducted, fingers unable to flex (non-dominant; dominant: 70%)',
 NULL, NULL,
 '38 CFR § 4.124a, DC 8515'),

('8516', 'Ulnar nerve — paralysis/incomplete', 'Neurological',
 NULL,
 'Mild incomplete paralysis (dominant or non-dominant)',
 NULL,
 'Moderate incomplete paralysis (non-dominant; dominant: 30%)',
 'Severe incomplete paralysis (non-dominant; dominant: 40%)',
 NULL,
 'Complete paralysis — griffin claw deformity, loss of flexion of ring and little finger, weakened hand grip (non-dominant; dominant: 60%)',
 NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8516'),

('8521', 'External popliteal (peroneal) nerve — paralysis', 'Neurological',
 NULL,
 'Mild incomplete paralysis',
 'Moderate incomplete paralysis',
 'Severe incomplete paralysis',
 'Complete paralysis — foot drop and slight droop of first phalanges of all toes, cannot dorsiflex the foot',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8521'),

('8620', 'Sciatic nerve — neuritis', 'Neurological',
 NULL,
 'Mild sciatic neuritis',
 'Moderate sciatic neuritis with characteristic pain',
 NULL,
 'Moderately severe neuritis',
 NULL,
 'Severe neuritis with marked muscular atrophy',
 NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8620'),

('8720', 'Sciatic nerve — neuralgia', 'Neurological',
 NULL,
 'Mild neuralgia',
 'Moderate characteristic pain',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8720'),

('6260', 'Tinnitus', 'Neurological',
 NULL,
 'Recurrent tinnitus — maximum schedular rating is 10% regardless of whether it is perceived in one ear or both',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.87, DC 6260'),

('6100', 'Hearing loss — bilateral', 'Neurological',
 'Level I hearing in both ears',
 'Various combinations of hearing levels (Table VI and VII) producing 10% under the rating table',
 'Various combinations producing 20%',
 'Various combinations producing 30%',
 'Various combinations producing 40%',
 'Various combinations producing 50%',
 'Various combinations producing 60%',
 'Various combinations producing 70%',
 'Various combinations producing 80%',
 'Various combinations producing 100%',
 '38 CFR § 4.85-4.87, DC 6100'),

-- ═══════════════════════════════════════════
-- PERIPHERAL NEUROPATHY
-- ═══════════════════════════════════════════

('8520-PN', 'Peripheral neuropathy — lower extremity (each)', 'Neurological',
 NULL,
 'Mild incomplete paralysis — decreased sensation, occasional numbness/tingling',
 'Moderate incomplete paralysis — frequent numbness, decreased reflexes, moderate sensory loss',
 NULL,
 'Moderately severe — significant sensory loss, muscle weakness affecting gait',
 NULL,
 'Severe with marked muscular atrophy',
 NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8520 (analogous)'),

('8515-PN', 'Peripheral neuropathy — upper extremity (each)', 'Neurological',
 NULL,
 'Mild incomplete paralysis — decreased sensation, occasional numbness/tingling in hands',
 NULL,
 'Moderate incomplete paralysis — frequent numbness, difficulty with fine motor tasks',
 NULL,
 'Severe incomplete paralysis — significant weakness, constant numbness, impaired grip',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.124a, DC 8515 (analogous)'),

-- ═══════════════════════════════════════════
-- GENITOURINARY
-- ═══════════════════════════════════════════

('7522', 'Erectile dysfunction', 'Genitourinary',
 'Deformity of the penis — loss of erectile power. Rated 0% but eligible for Special Monthly Compensation (SMC-K) adding ~$131/month',
 NULL,
 'Deformity of the penis with loss of erectile power — 20% only if deformity is present',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.115b, DC 7522 — Note: SMC-K payable under 38 USC 1114(k) for loss of use of creative organ'),

('7528', 'Malignant neoplasms — genitourinary system', 'Genitourinary',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '100% during active malignancy and for 6 months following cessation of treatment; then rated on residuals',
 '38 CFR § 4.115b, DC 7528'),

('7500', 'Kidney — removal of one', 'Genitourinary',
 NULL, NULL, NULL,
 'Removal of one kidney — minimum 30% rating',
 NULL, NULL,
 'Removal of one kidney with nephritis, infection, or pathology of the other kidney — 60%',
 NULL,
 'Renal dysfunction requiring regular dialysis OR precluding more than sedentary activity',
 'Renal dysfunction requiring regular dialysis AND severely impacting health',
 '38 CFR § 4.115a-b, DC 7500'),

-- ═══════════════════════════════════════════
-- DIGESTIVE
-- ═══════════════════════════════════════════

('7346', 'GERD / Hiatal hernia', 'Digestive',
 NULL,
 'Two or more of the symptoms for the 30% evaluation of less severity',
 NULL,
 'Persistently recurrent epigastric distress with dysphagia, pyrosis, and regurgitation, accompanied by substernal or arm or shoulder pain, productive of considerable impairment of health',
 NULL, NULL,
 'Symptoms of pain, vomiting, material weight loss and hematemesis or melena with moderate anemia, OR other symptom combinations productive of severe impairment of health',
 NULL, NULL, NULL,
 '38 CFR § 4.114, DC 7346'),

('7319', 'Irritable colon syndrome (IBS)', 'Digestive',
 'Mild — disturbances of bowel function with occasional episodes of abdominal distress',
 'Moderate — frequent episodes of bowel disturbance with abdominal distress',
 NULL,
 'Severe — diarrhea, or alternating diarrhea and constipation, with more or less constant abdominal distress',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.114, DC 7319'),

('7323', 'Ulcerative colitis', 'Digestive',
 NULL,
 'Moderate — infrequent exacerbations',
 NULL,
 'Moderately severe — frequent exacerbations',
 NULL, NULL,
 'Severe — numerous attacks per year and malnutrition, health only fair during remissions',
 NULL, NULL,
 'Pronounced — resulting in marked malnutrition, anemia, and general debility, OR with serious complications (liver abscess)',
 '38 CFR § 4.114, DC 7323'),

('7301', 'Peritoneal adhesions', 'Digestive',
 'Mild — pulling pain on attempting work or aggravated by movements of the body',
 'Moderate — pulling pain on attempting work, with occasional episodes of colic pain, nausea, constipation (perhaps alternating with diarrhea)',
 NULL,
 'Moderately severe — partial obstruction manifested by delayed motility of barium meal and less frequent and less prolonged episodes of pain',
 NULL,
 'Severe — definite partial obstruction with frequent and prolonged episodes of severe colic pain',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.114, DC 7301'),

('7332', 'Rectum and anus — fistula in ano', 'Digestive',
 'Healed or slight, without leakage',
 'Constant slight, or occasional moderate leakage',
 NULL,
 'Occasional involuntary bowel movements, necessitating wearing of pad',
 NULL, NULL,
 'Extensive leakage and fairly frequent involuntary bowel movements',
 NULL, NULL,
 'Complete loss of sphincter control',
 '38 CFR § 4.114, DC 7332'),

-- ═══════════════════════════════════════════
-- SKIN
-- ═══════════════════════════════════════════

('7806', 'Dermatitis or eczema', 'Skin',
 'Less than 5% of the entire body or less than 5% of exposed areas affected, and no more than topical therapy required during past 12 months',
 'At least 5% but less than 20% of the entire body, OR at least 5% but less than 20% of exposed areas affected, OR intermittent systemic therapy such as corticosteroids or other immunosuppressive drugs required for a total duration of less than 6 weeks during past 12 months',
 NULL,
 'At least 20% but less than 40% of the entire body, OR at least 20% but less than 40% of exposed areas affected, OR systemic therapy such as corticosteroids or immunosuppressive drugs required for a total duration of 6 weeks or more but not constantly during past 12 months',
 NULL, NULL,
 'More than 40% of the entire body, OR more than 40% of exposed areas affected, OR constant or near-constant systemic therapy such as corticosteroids or immunosuppressive drugs required during past 12 months',
 NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7806'),

('7800', 'Burn scars — head, face, or neck', 'Skin',
 NULL,
 'One characteristic of disfigurement',
 NULL,
 'Two or three characteristics of disfigurement',
 NULL,
 'Four or five characteristics of disfigurement',
 NULL, NULL,
 'Six or more characteristics of disfigurement',
 NULL,
 '38 CFR § 4.118, DC 7800'),

('7804', 'Scars — unstable or painful', 'Skin',
 NULL,
 'One or two scars that are unstable or painful',
 'Three or four scars that are unstable or painful',
 'Five or more scars that are unstable or painful',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7804'),

('7816', 'Psoriasis', 'Skin',
 'Less than 5% of entire body or exposed areas, topical therapy only',
 'At least 5% but less than 20% of body or exposed areas, or intermittent systemic therapy <6 weeks in past year',
 NULL,
 'At least 20% but less than 40% of body or exposed areas, or systemic therapy ≥6 weeks but not constant',
 NULL, NULL,
 'More than 40% of body or exposed areas, or constant/near-constant systemic therapy',
 NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7816'),

('7813', 'Dermatophytosis (ringworm/fungal)', 'Skin',
 'Less than 5% of body affected, topical therapy only',
 '5-20% of body or exposed areas, or intermittent systemic therapy',
 NULL,
 '20-40% of body or exposed areas, or systemic therapy ≥6 weeks',
 NULL, NULL,
 'More than 40% of body, or constant systemic therapy',
 NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7813'),

-- ═══════════════════════════════════════════
-- ENDOCRINE
-- ═══════════════════════════════════════════

('7913', 'Diabetes mellitus — type 2', 'Endocrine',
 NULL,
 'Manageable by restricted diet only',
 'Requiring insulin and restricted diet, OR oral hypoglycemic agent and restricted diet',
 NULL,
 'Requiring insulin, restricted diet, and regulation of activities',
 NULL,
 'Requiring insulin, restricted diet, and regulation of activities with episodes of ketoacidosis or hypoglycemic reactions requiring one or two hospitalizations per year or twice a month visits to a diabetic care provider, plus complications that would not be compensable if separately evaluated',
 NULL, NULL,
 'Requiring more than one daily injection of insulin, restricted diet, and regulation of activities with episodes of ketoacidosis or hypoglycemic reactions requiring at least 3 hospitalizations per year or weekly visits to a diabetic care provider, plus either progressive loss of weight and strength or complications that would be compensable if separately evaluated',
 '38 CFR § 4.119, DC 7913'),

('7903', 'Hypothyroidism', 'Endocrine',
 NULL,
 'Fatigability, or continuous medication required for control',
 NULL,
 'Fatigability, constipation, and mental sluggishness',
 NULL, NULL,
 'Muscular weakness, mental disturbance, and weight gain',
 NULL, NULL,
 'Cold intolerance, muscular weakness, cardiovascular involvement, mental disturbance (dementia, slowing of thought, depression), bradycardia, and sleepiness',
 '38 CFR § 4.119, DC 7903'),

('7900', 'Hyperthyroidism (Graves'' disease)', 'Endocrine',
 NULL,
 'Tachycardia which may be intermittent, and tremor, OR continuous medication required for control',
 NULL,
 'Tachycardia, tremor, and increased pulse pressure or blood pressure',
 NULL, NULL,
 'Emotional instability, tachycardia, fatigability, and increased pulse pressure or blood pressure',
 NULL, NULL,
 'Thyroid enlargement, tachycardia, eye involvement, muscular weakness, loss of weight, and sympathetic nervous system/cardiovascular/gastrointestinal symptoms',
 '38 CFR § 4.119, DC 7900'),

-- ═══════════════════════════════════════════
-- ADDITIONAL COMMON CONDITIONS
-- ═══════════════════════════════════════════

('5010', 'Traumatic arthritis', 'Musculoskeletal',
 'X-ray evidence without compensable limitation — minimum 10% per major joint affected',
 'Painful motion documented on examination — minimum 10% per joint group',
 'With occasional incapacitating exacerbations',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5010 (rated as DC 5003)'),

('5024', 'Tenosynovitis', 'Musculoskeletal',
 NULL,
 'Painful motion with X-ray confirmation',
 'Limited motion with painful use',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5024'),

('5019', 'Bursitis', 'Musculoskeletal',
 NULL,
 'Painful motion with X-ray confirmation or clinical evidence',
 'Limited motion with painful use',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5019'),

('7120', 'Varicose veins', 'Cardiovascular',
 'Asymptomatic palpable or visible varicose veins',
 'Intermittent edema of extremity or aching and fatigue in leg after prolonged standing or walking, with symptoms relieved by elevation of extremity or compression hosiery',
 'Persistent edema, incompletely relieved by elevation of extremity, with or without beginning stasis pigmentation or eczema',
 NULL,
 'Persistent edema and stasis pigmentation or eczema, with or without intermittent ulceration',
 NULL,
 'Persistent edema or subcutaneous induration, stasis pigmentation or eczema, and persistent ulceration',
 NULL, NULL,
 'Massive board-like edema with constant pain at rest (with or without stasis, ulceration)',
 '38 CFR § 4.104, DC 7120'),

('7117', 'Raynaud''s syndrome', 'Cardiovascular',
 NULL,
 'Characteristic attacks occurring one to three times a week',
 'Characteristic attacks occurring four to six times a week',
 NULL,
 'Characteristic attacks occurring at least daily',
 NULL,
 'Two or more digital ulcers plus autoamputation of one or more digits and history of characteristic attacks',
 NULL, NULL, NULL,
 '38 CFR § 4.104, DC 7117'),

('6204', 'Peripheral vestibular disorders', 'Neurological',
 NULL,
 'Occasional dizziness',
 NULL,
 'Dizziness and occasional staggering',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.87, DC 6204'),

('6205', 'Meniere''s disease', 'Neurological',
 NULL,
 'Hearing impairment with vertigo less than once a month, with or without tinnitus',
 NULL,
 'Hearing impairment with attacks of vertigo and cerebellar gait occurring from one to four times a month, with or without tinnitus',
 NULL, NULL,
 'Hearing impairment with attacks of vertigo and cerebellar gait occurring more than once weekly, with or without tinnitus',
 NULL, NULL,
 'Hearing impairment with attacks of vertigo and cerebellar gait occurring more than once weekly, with tinnitus, plus Meniere''s syndrome not controlled by medication',
 '38 CFR § 4.87, DC 6205'),

('7336', 'Hemorrhoids — external or internal', 'Digestive',
 'Mild or moderate hemorrhoids',
 'Large or thrombotic, irreducible, with excessive redundant tissue evidencing frequent recurrences',
 'With persistent bleeding and with secondary anemia, or with fissures',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.114, DC 7336'),

('5256', 'Ankylosis of the knee', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Favorable angle in full extension, or in slight flexion between 0 and 10 degrees',
 'In flexion between 10 and 20 degrees',
 'In flexion between 20 and 45 degrees',
 'Extremely unfavorable in flexion at an angle of 45 degrees or more',
 NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5256'),

('5262', 'Tibia and fibula impairment', 'Musculoskeletal',
 NULL,
 'Malunion with slight knee or ankle disability',
 'Malunion with moderate knee or ankle disability',
 'Malunion with marked knee or ankle disability',
 'Nonunion with loose motion, requiring brace',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5262'),

('7507', 'Renal tubular disorders', 'Genitourinary',
 NULL, NULL, NULL,
 'Albumin constant or recurring with hyaline and granular casts or red blood cells; OR transient or slight edema or hypertension',
 NULL, NULL,
 'Constant albuminuria with some edema; OR definite decrease in kidney function; OR hypertension at least 40% disabling',
 NULL,
 'Persistent edema and albuminuria with BUN 40-80mg%; OR creatinine 4-8mg%; OR generalized poor health',
 'Renal dysfunction requiring regular dialysis; OR precluding more than sedentary activity from age 60; BUN >80mg% or creatinine >8mg%',
 '38 CFR § 4.115a-b'),

('6502', 'Deviated nasal septum', 'Respiratory',
 NULL,
 '50% obstruction of the nasal passage on both sides or complete obstruction on one side',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.97, DC 6502'),

('5054', 'Total knee replacement', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Minimum rating — intermediate degrees of residual weakness, pain, or limitation of motion (rated by analogy)',
 NULL, NULL,
 'Chronic residuals consisting of severe painful motion or weakness in the affected extremity',
 NULL, NULL,
 '100% for 1 year following implantation of prosthesis; then rated on residuals, minimum 30%',
 '38 CFR § 4.71a, DC 5055'),

('5056', 'Total hip replacement', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Minimum rating — intermediate degrees of residual weakness, pain, or limitation of motion (rated by analogy)',
 NULL,
 'Markedly limited extension and adduction, or abduction, of the affected hip; moderately severe residuals of weakness, pain, or limitation',
 NULL,
 'Painful motion or weakness such as to require the use of crutches',
 NULL,
 '100% for 1 year following implantation; then rated on residuals, minimum 30%. If prosthetic replacement of femoral head or acetabulum: 90%',
 '38 CFR § 4.71a, DC 5054'),

('7804-PAIN', 'Scars — painful', 'Skin',
 NULL,
 'One or two painful scars',
 'Three or four painful scars',
 'Five or more painful scars',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7804'),

('7805', 'Scars — other (limitation of function)', 'Skin',
 NULL,
 'Scar causing limited motion — rated on limitation of function of affected part',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.118, DC 7805'),

('5290', 'Temporomandibular joint (TMJ) disorder', 'Musculoskeletal',
 NULL,
 'Inter-incisal range 31-40mm OR lateral excursion 0-4mm',
 'Inter-incisal range 21-30mm',
 'Inter-incisal range 11-20mm',
 'Inter-incisal range 0-10mm',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.150, DC 9905'),

('6311', 'Chronic fatigue syndrome', 'Systemic',
 NULL,
 'Debilitating fatigue, cognitive impairments, or other symptoms controlled by continuous medication',
 'Debilitating fatigue, cognitive impairments, or other symptoms that are nearly constant and restrict routine daily activities by less than 25% of pre-illness level',
 NULL,
 'Debilitating fatigue, cognitive impairments, or other symptoms that are nearly constant and restrict routine daily activities to 50-75% of pre-illness level, OR symptoms that wax and wane resulting in periods of incapacitation of at least 2 but less than 4 weeks total per year',
 NULL,
 'Debilitating fatigue, cognitive impairments, and other symptoms that are nearly constant and restrict routine daily activities to less than 50% of pre-illness level, OR symptoms that wax and wane resulting in periods of incapacitation of at least 4 but less than 6 weeks total per year',
 NULL, NULL,
 'Debilitating fatigue, cognitive impairments, and other symptoms that are nearly constant and so severe as to restrict routine daily activities almost completely, OR symptoms that are nearly constant and so severe as to result in periods of incapacitation of at least 6 weeks total per year',
 '38 CFR § 4.88b, DC 6354'),

('5025', 'Fibromyalgia', 'Musculoskeletal',
 NULL,
 'Widespread musculoskeletal pain and tender points, with or without associated fatigue, sleep disturbance, stiffness, paresthesias, headache, IBS, depression, anxiety, or Raynaud''s-like symptoms that require continuous medication for control',
 'Episodic, with exacerbations often precipitated by environmental or emotional stress or by overexertion, but symptoms that are present more than one-third of the time',
 NULL,
 'Constant or nearly constant widespread musculoskeletal pain and tender points, with associated fatigue, sleep disturbance, stiffness, paresthesias, headache, IBS, depression, anxiety, or Raynaud''s-like symptoms that are refractory to therapy',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5025'),

('8910', 'Epilepsy — grand mal (generalized tonic-clonic)', 'Neurological',
 NULL,
 'Confirmed diagnosis with a history of seizures',
 'At least 1 major seizure in the last 2 years, OR at least 2 minor seizures in the last 6 months',
 NULL,
 'At least 1 major seizure in the last 6 months, OR 2 major seizures in the last year, OR at least 5-8 minor seizures weekly',
 NULL,
 'Averaging at least 1 major seizure in 4 months over the last year, OR 9-10 minor seizures per week',
 NULL,
 'Averaging at least 1 major seizure per month over the last year',
 'Averaging at least 1 major seizure per month over the last year with severe neurological impairment',
 '38 CFR § 4.124a, DC 8910'),

('5051', 'Total shoulder replacement', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Minimum rating — intermediate degrees of residual weakness, pain, or limitation of motion',
 NULL,
 'Chronic residuals consisting of severe painful motion or weakness (non-dominant)',
 NULL, NULL, NULL,
 '100% for 1 year following implantation; then rated on residuals, minimum 30%',
 '38 CFR § 4.71a, DC 5051'),

('5205', 'Elbow — ankylosis', 'Musculoskeletal',
 NULL, NULL, NULL,
 'Favorable ankylosis at an angle between 90-70 degrees (non-dominant)',
 'Intermediate ankylosis at an angle greater than 90 degrees or between 70-50 degrees (non-dominant)',
 'Unfavorable ankylosis at angle less than 50 degrees or with complete loss of supination or pronation (non-dominant)',
 NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5205'),

('5208', 'Forearm — flexion limited to 90 degrees and extension limited to 75 degrees', 'Musculoskeletal',
 NULL, NULL,
 'Forearm flexion limited to 100 degrees with extension limited to 45 degrees (non-dominant)',
 NULL,
 'Forearm flexion limited to 90 degrees with extension limited to 75 degrees (non-dominant)',
 NULL, NULL, NULL, NULL, NULL,
 '38 CFR § 4.71a, DC 5208'),

('7110', 'Aortic aneurysm', 'Cardiovascular',
 NULL, NULL, NULL, NULL, NULL, NULL,
 '5 cm or larger in diameter; OR if surgically corrected, evaluate according to residuals',
 NULL, NULL,
 'Precluding exertion; OR with general ill health',
 '38 CFR § 4.104, DC 7110'),

('6354', 'Chronic fatigue syndrome (alternative code)', 'Systemic',
 NULL,
 'Controlled by continuous medication',
 'Restricts daily activities by <25% OR incapacitating episodes <2 weeks/year',
 NULL,
 'Restricts daily activities to 50-75% OR incapacitating episodes 2-4 weeks/year',
 NULL,
 'Restricts daily activities to <50% OR incapacitating episodes 4-6 weeks/year',
 NULL, NULL,
 'Nearly completely restricts daily activities OR incapacitating episodes ≥6 weeks/year',
 '38 CFR § 4.88b, DC 6354'),

('7914', 'Neoplasm — malignant (endocrine)', 'Endocrine',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 '100% during active malignancy; then rated on residuals after treatment cessation',
 '38 CFR § 4.119, DC 7914');
